# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.omnibus.chef_version = '12.4'

  config.vm.provision "chef_zero" do |chef|
    chef.run_list = [
      "recipe[vt-sailbot::default]"
    ]
  end

end
